### ISSUE TITLE
System.HashCode in DiscUtils.Nfs causes conflicts when targeting .Net Core 2+

### ISSUE THREAD

**Issue by fitdev** [DiscUtils/DiscUtils#139]
Latest versions of .Net Core already have a type HashCode under System namespace. So, the presence of the same type in DiscUtils.Nfs is causing compile time error due to name conflict (type with the same name defined in 2 different assemblies). So, can you please rename this type, in your lib, or alternatively not include it at all (for versions targeting .Net Core 2.1+ since it is already included with the framework).

**Comment by LordMike** [comment]
Jebus. We use it for the same things?

If so. We should exclude it in those targets that have it and use theirs instead.

We risk behavioral changes, but that should be a non issue for hashcodes.


________________________________

**Comment by gfs** [comment]
Bump. This is still a conflict with .NET Core 3.1 if you include DiscUtils.NFS (or complete).

**Comment by LordMike** [comment]
Could you, @gfs (or @fitdev), provide a PR ?

**Comment by gfs** [comment]
@LordMike there are two options.

1. A breaking change that would move the HashCode defined in DiscUtils.Nfs to another namespace under discutils instead of system. If some consumer of the library were then to be relying on DiscUtils implementation of System.HashCode, they would have to update their references. It's arguable this is a better design decision to not export into the System namespace going forward.

2. Use preprocessor directives to only include HashCode where it is known to be not implemented.  I implemented 2 in #193.

**Comment by zivillian** [comment]
If I'm correct the implementation will behave identically on all platforms, since the code of both implementations is actually the same: https://source.dot.net/#System.Private.CoreLib/HashCode.cs,5f9e3dc86db22de1

**Comment by gfs** [comment]
I think the remaining issue with Option 2 is that it will cause a conflict if users are using another library that also exports System.HashCode.

**Comment by LordMike** [comment]
It actually makes me wonder why Nfs has a public HashCode in the first place.. I'm inclined to go with your no. 1, @gfs. Move its namespace, make it internal.. if no other DiscUtils library is using this (they shouldn't.. as it's in Nfs).. then just go with that.

**Comment by gfs** [comment]
Sounds good.

#193 now implements option 1.
