### ISSUE TITLE
Support for reading used VM images

### ISSUE THREAD

**Issue by zivillian** [DiscUtils/DiscUtils#24]
### Introduction
I have a set of patches, which enable reading of locked files and filesystems in use by a Virtual Machine. Those patches enable us to get a (nearly) exact filesystem usage for most of the VMs and Volumes.

I am aware, that there might be many conditions of inconsitent data, but since we are only interested in the filesystem usage and not the content this seems to be working. We are collecting the usage every hour, so we are able to ignore temporary errors and obviously incorrect results.

#### Vhd & Vhdx
The images are opened by the hypervisor and locked for writing, so we need to change FileShare to ReadWrite.

#### Ext2/3/4
A mounted ext filesystem always has the IncompatibleFeature NeedsRecovery - this is set when mounting an ext fs. We need to introduce a flag, to ignore this for our use case.

#### Ntfs
We had some errors reading the SecurityDesciptors. Since they are only used when explicitly requesting them, or creating new files or directories, we introduced an OnErrorReadOnly options, similar to the linux mount option.

### Stability
We have run those patches for nearly 3 months on a farm of about 100 hypervisors with ~1300 virtual machines, ~2000 images and ~3000 filesystems. There are still some errors and unsupported filesystems, but we're trying to eleminate them over the next few months.

### Conclusion
Do you see any chance to integrate our changes into the "official" DiscUtils library? Currently we are building our own package, but this got more complex due to the recent migration to multiple nuget packages.

**Comment by LordMike** [comment]
Seems like quite some operation you have running.

**VHD(X)** isn't it possible today to provide a stream to the VHD(x) parsers?.. If so, it's up to the caller to sucessfully open the file - if not, that's a bug.. :)

**Ext** all for it. All parsers should have settings objects with all possible configurations for the given parser.

**Ntfs** would it be possible to learn more about why they're failing? Is it bad references (due to in-use filesystems) or is it more severe (a bug on DU's part)?

As for the complexity, it should be possible for you to build the exact same packages with your changes in, using msbuild. The build script in `appveyor.yml` should show how this can be done. Did you encounter specific issues, or is it more an internal thing of distributing 1 vs. 20 files :)?

**Comment by zivillian** [comment]
#### VHD(X)
It is possible to open an image from a stream, but this is not working with differencing images. The image then only contains a reference to the parent disks filename (which may even be in a different location).
I also have to know in advance, which specific image type is contained in a file - currently we are using `VirtualDisk.OpenDisk(path, FileAccess.Read)` whis does all the heavy work like detecting the image type and finding parent images etc.

#### Ntfs
If I remember correctly, there was an error reading a hash index. We gave up after debugging multiple levels an hours, but I will try to create an unit test when I can find a broken image. The filesystem passed all FS checkers (even from MS) but the error went away when we mounted the vhd. So for now I'm pretty sure the error occured due to beeing in-use.

#### Ext
I will create a PR.

The complexity concerns are based on distributing many more files and possible version conflicts. @qmfrederik had a single nuspec file, where we just changed the package id - this is more error prone for the new repo (and I don't want to build, merge and update my own version without a real need). The `appveyor.yml` worked like a charm, so many thanks for this.

**Comment by zivillian** [comment]
- [x] VHD(X) was fixed in #52 
- [x] Ntfs seems to be fixed with #27 
- [ ] Ext will be fixed with #65
